# Set nginx base image
FROM nginx

# File Author / Maintainer
LABEL AUTHOR="Blair Garrett<blair.garrett1@gmail.com>"

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf